[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm run start"
  port = 8888
  targetPort = 3000
  publish = "build"
  framework = "react"
  functionsPort = 9999

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 